<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Couldn't create screenshot]]>
    </line>
    <line>
      <![CDATA[Connection refused: connect]]>
    </line>
    <line>
      <![CDATA[Couldn't create screenshot]]>
    </line>
    <line>
      <![CDATA[Connection refused: connect]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="4497" started-at="2013-07-11T01:31:01Z" finished-at="2013-07-11T01:31:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4497" started-at="2013-07-11T01:31:01Z" finished-at="2013-07-11T01:31:06Z">
      <class name="selenium.AjaxSeleniumTest">
        <test-method status="PASS" signature="attachScreenshotListener(java.lang.String, java.lang.String, org.testng.ITestContext)[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="attachScreenshotListener" is-config="true" duration-ms="198" started-at="2013-07-11T03:31:01Z" finished-at="2013-07-11T03:31:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4444]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@1b64deb]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attachScreenshotListener -->
        <test-method status="FAIL" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="setUp" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:01Z" finished-at="2013-07-11T03:31:01Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:102)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:134)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:103)
	at com.thoughtworks.selenium.SeleneseTestNgHelper.setUp(SeleneseTestNgHelper.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[Couldn't create screenshot]]>
            </line>
            <line>
              <![CDATA[Connection refused: connect]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="getSelenium(boolean)[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="getSelenium" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSelenium -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="setUp" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="setTestContext(java.lang.reflect.Method)[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="setTestContext" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTestContext -->
        <test-method status="SKIP" signature="testAjaxTestCase1()[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="testAjaxTestCase1" duration-ms="1" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAjaxTestCase1 -->
        <test-method status="SKIP" signature="checkForVerificationErrors()[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="checkForVerificationErrors" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkForVerificationErrors -->
        <test-method status="FAIL" signature="selectDefaultWindow()[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="selectDefaultWindow" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:04Z" finished-at="2013-07-11T03:31:04Z">
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: Connection refused: connect
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:121)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:101)
	at com.thoughtworks.selenium.DefaultSelenium.selectWindow(DefaultSelenium.java:370)
	at com.thoughtworks.selenium.SeleneseTestNgHelper.selectDefaultWindow(SeleneseTestNgHelper.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:69)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:378)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:473)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:203)
	at sun.net.www.http.HttpClient.New(HttpClient.java:290)
	at sun.net.www.http.HttpClient.New(HttpClient.java:306)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:995)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:931)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:849)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1090)
	at com.thoughtworks.selenium.HttpCommandProcessor.getOutputStreamWriter(HttpCommandProcessor.java:149)
	at com.thoughtworks.selenium.HttpCommandProcessor.getCommandResponseAsString(HttpCommandProcessor.java:176)
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:118)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
            <line>
              <![CDATA[Couldn't create screenshot]]>
            </line>
            <line>
              <![CDATA[Connection refused: connect]]>
            </line>
          </reporter-output>
        </test-method> <!-- selectDefaultWindow -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:selenium.AjaxSeleniumTest@176feaf]" name="tearDown" is-config="true" duration-ms="0" started-at="2013-07-11T03:31:06Z" finished-at="2013-07-11T03:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- selenium.AjaxSeleniumTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
